-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Gép: 127.0.0.1
-- Létrehozás ideje: 2025. Ápr 13. 19:50
-- Kiszolgáló verziója: 10.4.32-MariaDB
-- PHP verzió: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Adatbázis: `receptek`
--

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `admin`
--

CREATE TABLE `admin` (
  `id` int(11) NOT NULL,
  `uname` varchar(50) DEFAULT NULL,
  `passw` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `admin`
--

INSERT INTO `admin` (`id`, `uname`, `passw`) VALUES
(1, 'admin', '$2b$10$GCf5FVje8RCEMkpumbaoZ.M6FZtDCxxRAdo5PmjsaBbBHLWQiAYZu');

-- --------------------------------------------------------

--
-- Tábla szerkezet ehhez a táblához `recept`
--

CREATE TABLE `recept` (
  `id` int(11) NOT NULL,
  `tipus` varchar(25) NOT NULL,
  `nev` varchar(100) NOT NULL,
  `tagek` varchar(75) DEFAULT NULL,
  `ido` int(11) NOT NULL,
  `adag` int(11) NOT NULL,
  `hozzavalok` text NOT NULL,
  `elkeszites` text NOT NULL,
  `kepnev` varchar(100) DEFAULT NULL,
  `forras` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_hungarian_ci;

--
-- A tábla adatainak kiíratása `recept`
--

INSERT INTO `recept` (`id`, `tipus`, `nev`, `tagek`, `ido`, `adag`, `hozzavalok`, `elkeszites`, `kepnev`, `forras`) VALUES
(1, 'főétel', 'Krémes fokhagymás tészta', 'tészta;sajtos', 35, 3, '{\"olivaolaj\":\"2 teáskanál\",\"fokhagyma\":\"4 gerezd, apróra vágva\",\"vaj\":\"2 evőkanál\",\"víz\":\"~750 ml\",\"bors\":\"0.5 teáskanál (fekete őrölt)\",\"só\":\"0.25 teáskanál\",\"tészta\":\"250 g\",\"parmezán sajt\":\"100 g\",\"tejszín\":\"200 ml\",\"petrezselyem\":\"1.5 evőkanál\"}', '1. Melegítsünk olívaolajat egy közepes serpenyőben közepes lángon. Adjuk hozzá a fokhagymát, és keverjük, amíg illatos nem lesz, 1-2 percig. Adjuk hozzá a vajat, és folyamatosan kevergetve olvasszuk meg.\n2. Öntsük hozzá a vizet; adjunk hozzá borsot és sót. Forraljuk fel. Adjuk hozzá a spagettit (vagy a választott tésztát), és időnként megkeverve főzzük, amíg puha, de harapható nem lesz, kb. 12 percig. Adjunk hozzá még vizet, ha a tészta elkezd ragadni a serpenyőhöz.\n3. Adjuk hozzá a parmezán sajtot, a tejszínt és a petrezselymet, és keverjük össze, amíg alaposan össze nem áll. Azonnal tálaljuk.', 'kremesFokhagymasTeszta.jpg', 'https://www.allrecipes.com/recipe/269500/creamy-garlic-pasta/'),
(2, 'főétel', 'Sült feta tészta', 'tészta;sajtos', 40, 4, '{\"tészta\":\"350 g\",\"víz\":\"~700 ml\",\"feta sajt\":\"1 tömb (~250 g)\",\"paradicsom\":\"0.5l db (cseresznyeparadicsom)\",\"olivaolaj\":\"1 evőkanál\",\"só\":\"0.5 teáskanál\",\"bors\":\"0.25 teáskanál (fekete őrölt)\",\"fokhagyma\":\"2 gerezd, apróra vágva\",\"bazsalikom\":\"25 g\"}', 'A folyamat egyszerű, és ez az, ami szerintünk ezt a receptet olyan nagyszerűvé teszi! A következőkre lesz szükségünk:\n1. Melegítsük elő a sütőt 200 °C-ra.\n2. Tegyük a fetatömböt a tepsibe. - helyezzük a feta sajtblokkot a tál közepére.\n3. Adjuk hozzá a tésztát és a vizet - tegyük a száraztésztát a sütőtálba (a feta tömb körül), öntsük rá a vizet a nyers tésztára, és óvatosan keverjük össze a tésztát és a vizet (ügyelve arra, hogy a tészta ne kerüljön a feta alá vagy tetejére), hogy az összes tészta elmerüljön a folyadékban.\n4. Adjuk hozzá a cseresznyeparadicsomot, az EVOO-t, sót és borsot - szórjuk a cseresznyeparadicsomot a tészta tetejére, és locsoljunk meg mindent az EVOO-val, sóval és borssal.\n5. Szorosan lefedjük + sütjük - a tepsit a lehető legszorosabban lefedjük fóliával, és 200 fokon 40 percig sütjük.\n6. Adjuk hozzá a fokhagymát és a bazsalikomot + keverjük össze - miután befejeztük a sütést, vegyük le a fóliát, adjuk hozzá a felaprított fokhagymát és a friss bazsalikomot, és keverjünk össze mindent, amíg jól össze nem keveredik.\nTálalja és élvezze!', 'sultFetaTeszta.jpeg', 'https://fedandfit.com/feta-pasta/'),
(3, 'főétel', 'Borsós csirketokány', '', 25, 4, '{\"tészta\":\"200 g\",\"vöröshagyma\":\"1 fej(~120g)\",\"fokhagyma\":\"3 gerezd\",\"csirkemell\":\"400g\",\"paradicsom\":\"1 teáskanál (sürítettparadicsom)\",\"só\":\"csipet\",\"bors\":\"csipet\",\"tejszín\":\"300ml (habt)\",\"zöldborsó\":\"200 g (mirelit)\",\"vaj\":\"30 g\"}', 'A borsós csirketokány elkészítéséhez a zsírt melegítünk egy serpenyőben. Hozzáadjuk a finomra vágott vöröshagymát és fokhagymát, és közepes hőfokon 5 percig dinszteljük. Hozzáadjuk a kb. 2 cm-es csíkokra vágott csirkemellet. Sózzuk, borsozzuk, és erős hőfokon 2 perc alatt jól lepirítjuk. Mehet hozzá a sűrített paradicsom is, és újabb 1-2 percig pirítjuk. Felöntjük a tejszínnel, hozzáadjuk a borsót, a vajat, és további 6 perc alatt készre főzzük.\nA szarvacskatésztát kifőzzük a csomagoláson írtak szerint, és ezzel tálaljuk a ragut. ', 'borsosCsirketokany.jpg', 'https://streetkitchen.hu/hust-hussal/borsos-csirketokany/'),
(4, 'desszert', 'Túrós pite', 'édes', 65, 8, '{\"liszt\":\"60 dkg\",\"cukor\":\"30 dkg\",\"sütőpor\":\"1 csomag\",\"vaj\":\"30 dkg\",\"tejföl\":\"1 pohár\",\"tojás\":\"5db\",\"túró\":\"50dkg\",\"vaníliás cukor\":\"1 csomag\",\"citrom\":\"1db (reszelt héj)\",\"zöldborsó\":\"200 g (mirelit)\"}', '1. A túrós pite elkészítéséhez összekeverjük a lisztet, a cukrot és a sütőport, majd belemorzsoljuk a hideg vajat.\n2. Hozzáadjuk a tejfölt és a tojássárgákat, és gyors mozdulatokkal összekeverjük, összegyúrjuk a tésztát, majd folpackba csomagolva a hűtőbe tesszük, és hagyjuk pihenni. Ez idő alatt elkészítjük a túrós tölteléket.\n3. A töltelékhez összekeverjük a túrót, a tojássárgáját, a cukrot, a vaníliás cukrot, a lisztet és a citrom lereszelt héját és a mazsolát. A tojásfehérjét kemény habbá verjük, és a túrós masszába keverjük.\n4. Tepsibe terítjük a tészta 2/3-ad részét kinyújtva (nem kell túl vastagon), ezen elegyengetjük a túrós tölteléket. A tetejét négyzetrácsosan befedjük a maradék tésztával (vagy ráborítjuk vékonyra van nyújtva).\n5. Megszurkáljuk, és 170 fokra előmelegített sütőben 35-40 percig sütjük. Még forrón megszórjuk porcukorral.', 'turosPite.jpg', 'https://www.mindmegette.hu/recept/turos-pite-ii'),
(5, 'leves', 'Zöldségleves tortillachipsszel', '', 45, 5, '{\"olivaolaj\":\"2 evőkanál\",\"vöröshagyma\":\"1 fej(~120g)\",\"fokhagyma\":\"4 gerezd\",\"kömény\":\"0.25-0.5 teáskanál (őrölt római)\",\"chilipor\":\"2-3 teáskanál\",\"sárgarépa\":\"1 db, felkarikázva\",\"burgonya\":\"1 db, felkockázva\",\"paradicsom\":\"35 dkg, kockákra vágva\",\"cukkini\":\"1 db, felkockázva\",\"káposzta\":\"0.25 fej, csíkokra szelve\",\"víz\":\"1 l\",\"kukorica\":\"1 db\",\"zöldbab\":\"10 db\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"korianderzöld\":\"4-6 evőkanál\",\"salsa\":\"ízlésre\",\"tortillachips\":\"ízlésre\"}', '1. Az olajat vastag aljú serpenyőben vagy fazékban felforrósítjuk.\r\n2. Beledobjuk a vöröshagymát a fokhagymával együtt, és néhány perc alatt üvegesre pároljuk. Meghintjük a római köménnyel és chiliporral. Hozzákeverjük a felaprított sárgarépát, burgonyát, paradicsomot, cukkinit meg káposztát, és időnként megkeverve 2 percig pirítjuk.\r\n3. Felöntjük vízzel. Fedő alatt, közepes lángon, 20 perc alatt puhára főzzük a zöldségeket.\r\n4. Ha szükségesnek látjuk, kevés vizet öntünk hozzá, belekeverjük a kukoricát és a zöldbabot, majd további 5-10 perc alatt a babot is puhára pároljuk. Sóval, borssal ízesítjük, nem feledkezve meg arról, hogy a tortillachips is sós.\r\n5. Mélytányérba merjük, és apróra vágott friss korianderzöldet hintünk a tetejére. Kevés salsát kanalazunk a tetejére, és egy marék tortillachipset kínálunk mellé.', 'zoldseglevesTortillachipsszel.jpg', 'Szakácskönyv Mexikói Konyha, több mint 100 fontosabb recept, 8. oldal (https://bookline.hu/product/home.action?_v=Szakacskonyvtar_Mexikoi_konyha&type=22&id=101359)'),
(6, 'desszert', 'Holland fánk', 'édes', 50, 1, '{\"liszt\":\"30 dkg\",\"cukor\":\"2 evőkanál\",\"alma\":\"1 db\",\"élesztő\":\"1 csomag(7g)\",\"tej\":\"2,5 dl\",\"tojás\":\"1db\",\"só\":\"1 csipet\",\"narancs\":\"1 db (reszelt héj)\",\"mazsola\":\"10 dkg\",\"porcukor\":\"tálaláshoz\",\"olaj\":\"a sütéshez\"}', '1. Meglangyosítjuk a tejet. Beletesszük a két evőkanál cukrot, beleszórjuk az élesztőt, elkeverjük, és langyos helyen hagyjuk tíz percig állni.\n2. Közben az almát meghámozzuk és apróra vágjuk.\n3. Keverőtálba tesszük a lisztet, hozzáöntjük a felhabosodott élesztős tejet, a villával felvert tojást, a csipet sót, és habverővel összedolgozzuk. Végül beleforgatjuk az apróra vágott almát, a narancs reszelt héját és a mazsolát. Letakarva egy órán át hagyjuk kelni. \n4. Egy serpenyőben bő olajat forrósítunk. Két evőkanalat belemártunk, majd a tésztából kiveszünk egy kanálnyit, megformázzuk a két kanállal, beletesszük a forró olajba. Ha pirulni kezd, megfordítjuk. Konyhai kéztörlőre szedve hagyjuk lecsepegni, végül megforgatjuk porcukorban.', 'HollandFank.png', 'https://www.mindmegette.hu/alapetelek/oliebollen-holland-fank-recept'),
(7, 'főétel', 'Hagyományos káposztás tészta', 'tészta', 45, 4, '{\"káposzta\":\"1kg (fejeskáposzta)\",\"étolaj\":\"7 dl\",\"só\":\"ízlésre\",\"bors\":\"1 teáskanál\",\"tészta\":\"50 dkg (fodros kockatészta)\"}', '1. A káposzta külső leveleit eltávolítjuk, majd negyedeljük. A torzsáját kivágjuk és a leveleit felkockázzuk.\n2. Egy nagyobb fazékban olajat hevítünk, erre dobjuk rá a kockázott káposztát, alaposan sózzuk, és folyamatos kevergetés mellett pirítjuk, amíg a káposzta kb. a felére esik össze, közben frissen őrölt borssal megszórjuk.\n3. Amíg pirul a káposzta egy lábasban vizet forralunk kevés olajjal, majd ha felforrt, sózzuk a főzővizet, és puhára főzzük a tésztát. Leszűrjük, és a pirított káposztához keverjük. Frissen tálaljuk.', 'hagyomanyosKaposztasTeszta.jpg', 'https://www.mindmegette.hu/recept/hagyomanyos-kaposztas-teszta'),
(8, 'reggeli', 'Rántotta', '', 10, 1, '{\"olaj\":\"0.5 teáskanál\",\"vaj\":\"1 teáskanál\",\"tojás\":\"3 db\",\"só\":\"1 csipet\"}', '1. Egy serpenyőt közepes lángon melegíteni kezdünk. Beleöntjük az olajat, majd hozzáadjuk a vajat. Amíg a vaj felhabzik, a tojásokat egy keverőtálba öntjük, sózzuk, villával kissé felverjük (nem kell, hogy teljesen elkeveredjen a sárgája a fehérjével).\n2. A keveréket a habzó vajra öntjük, és körkörös mozdulatokkal keverve megsütjük. Ügyeljünk arra, hogy ne süssük szárazra (3 db tojás esetén nagyjából 1-2 perc a sütési idő).\n3. Végül ízlés szerint megszórhatjuk egy kevés őrölt pirospaprikával vagy akár sajttal. Pirítóssal, vagy friss kenyérrel tálaljuk.', 'rantotta.jpg', 'https://www.mindmegette.hu/recept/rantotta'),
(9, 'leves', 'Póréhagyma-krémleves pirítóssal', '', 45, 4, '{\"vaj\":\"2 evőkanál\",\"póréhagyma\":\"2 db\",\"víz\":\"1 liter\",\"burgonya\":\"2 db\",\"babérlevél\":\"1 db\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"tejszín\":\"4 evőkanál\",\"snidling\":\"ízlésre\"}', '1. A vajat egy lábasban megolvasztjuk, és megfuttatjuk benne a megtisztított, apróra vágott póréhagymát. Addig főzzük, míg megpuhul (ez kb. 10 perc).\n2. Felöntjük az alaplével, hozzáadjuk a meghámozott, felkockázott burgonyát és a babérlevelet. Sózzuk, borsozzuk, és felforraljuk, majd közepes lángon kb. 15 percig főzzük, vagy amíg a burgonya teljesen megpuhul.\n3. Lehúzzuk a levest a tűzről, hagyjuk kissé hűlni, majd eltávolítjuk belőle a babérlevelet.\n4. A levest simára turmixoljuk, majd visszatesszük a tűzre. Folyamatos kevergetés mellett hozzáadjuk a tejszínt, és felforraljuk. Ha szükséges, ismét sózzuk, borsozzuk. Ezután lehúzzuk a tűzről, és tányérokba vagy kis tálkákba merve kínáljuk.\n5. Megszórjuk az apróra vágott snidlinggel, és pirított kenyérszeleteket kínálunk mellé.', 'porehagymaKremlevesPiritossal.jpg', 'https://www.mindmegette.hu/recept/porehagymakremleves-piritossal'),
(10, 'főétel', 'Csirke Cordon bleu sonkás rizzsel', '', 90, 6, '{\"csirkemell\":\"1.2 kg\",\"sonka\":\"40 dkg\",\"sajt\":\"30 dkg\",\"finomliszt\":\"12 dkg\",\"tojás\":\"5 db\",\"zsemlemorzsa\":\"20 dkg\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"olaj\":\"3 dl (napraforgó olaj)\",\"rizs\":\"30 dkg\",\"sonka\":\"10 dkg\",\"vöröshagyma\":\"1 db (közepes)\",\"vaj\":\"5 dkg\",\"víz\":\"3 dl\"}', '1. Megtisztítjuk, megmossuk, vékony szeletekre vágjuk, majd folpackban kiklopfoljuk a húst. Mindkét oldalát ízlés szerint sózzuk, borsozzuk.\n2. Előkészítjük a (30 dkg) sonkát, lereszeljük a sajtot, majd a hússzeletekre helyezünk 2 szelet sonkát és egy maréknyi sajtot, és szorosan feltekerjük (ha kisebbek a szeletek, akkor érdemes fogpiszkálóval összetűzni, hogy ne nyíljanak szét). Ha kész vagyunk, akkor tálcára helyezzük a roládokat, folpackkal fedjük, majd hűtőben pihentetjük, közben elkészítjük a köreteket.\n3. Kb. 30-40 perc pihentetés után (duplán) bepanírozzuk a húsokat a következőképpen: először lisztben forgatjuk meg, majd sóval felvert tojásba, zsemlemorzsába, majd ismét tojásba, és végül zsemlemorzsában hempergetjük meg a húsokat.\n4. Felhevítjük az olajat egy serpenyőben, és minden oldalát aranybarnára sütjük közepes hőfokozaton (kb. 20 perc).\n5. Átmossuk a rizst, szűrőn lecsepegtetjük. Megtisztítjuk, megmossuk a vöröshagymát felaprítjuk, a (10 dkg) sonkát 1x1 cm-es kockákra vágjuk.\n6. A vajat felhevítjük egy lábasban, majd beletesszük a hagymát, és üvegesre pároljuk. Utána hozzáadjuk a sonkát, majd a rizst, és pár percig pirítjuk.\n7. Sózzuk, borsozzuk, felöntjük vízzel, és az egészet puhára főzzük (rizsfajtától függ, de kb. 10-15 perc). Tálalás előtt még fedő alatt pár percig pihentetjük.', 'csirkeCordonBleuSonkasRizzsel.jpg', 'https://www.nosalty.hu/recept/csirke-cordon-bleu-zoldkorettel-sonkas-rizzsel?adag=6#ingredients'),
(11, 'reggeli', 'Tükörtojás', '', 5, 2, '{\"tojás\":\"2 db\",\"olaj\":\"2 evőkanál (napraforgó olaj)\"}', '1. Az olajat egy serpenyőben kellőképp felforrósítjuk és óvatosan beleütjük a tojásokat.\n2. Keverés nélkül készre sütjük, míg a tojásfehérje megsül, de a sárgája folyós marad.\n3. Hogy jobban átsüljön, a tojásfehérjét egy villa segítségével óvatosan megmozgathatjuk.', 'tukortojas.jpg', 'https://www.nosalty.hu/recept/tukortojas?adag=2#ingredients ; https://streetkitchen.hu/basic/tukortojas-sutese/'),
(12, 'desszert', 'Csokis cupcake', 'édes', 45, 12, '{\"vaj\":\"15 dkg (puha)\",\"cukor\":\"12 dkg + 2 evőkanál\",\"tojás\":\"3 db\",\"liszt\":\"15 dkg\",\"sütőpor\":\"1.5 teáskanál\",\"kakaópor\":\"3 evőkanál (púpos)\",\"tejszín\":\"2 dl\",\"étcsokoládé\":\"20 dkg\"}', '1. A vajat habosra keverjük a cukorral, és egyenként beledolgozzuk a tojásokat. A lisztet elvegyítjük a sütőporral és a kakaóval, majd a vajas keverékbe forgatjuk.\n2. A sütőt előmelegítjük 180 fokra. A tészta masszját egy 12 részes muffintepsi papírkapszlikkal kibélelt mélyedéseibe kanalazzuk, majd kb. 20 perc alatt megsütjük. A muffinokat kiemeljük a tepsiből, és a rácson hűlni hagyjuk.\n3. A krémhez felverjük a tejszínt a cukorral, majd hozzákeverjük a gőz felett felolvasztott csokoládét. A krémet lehűtjük, majd habzsákba töltjük, és a muffinok tetejére nyomjuk. Végül mindet megszórjuk csokoládédarabokkal.', 'csokisCupcake.jpg', 'https://www.mindmegette.hu/recept/csokis-cupcake'),
(13, 'reggeli', 'Amerikai palacsinta', 'édes', 7, 4, '{\"finomliszt\":\"225 g\",\"tojás\":\"1 db\",\"tej\":\"3 dl\",\"sütőpor\":\"1 csomag\",\"cukor\":\"3 evőkanál\",\"vaníliás cukor\":\"1 csomag\",\"fahéj\":\"1 késhegynyi\",\"olaj\":\"1 evőkanál (napraforgó olaj)\"}', '1. Az összes hozzávalót beletesszük a turmixba, és alaposan összemixeljük. Érdemes 2 részletben hozzáadni a tejet és a lisztet, így egyszerűbb, hatékonyabb.\n2. Felforrósítunk és beolajozunk egy teflon serpenyőt. A tésztakeverékből 2-3 korongot csorgatunk bele. A turmix kiöntője segítségével egyszerű adagolni. Aranybarnára sütjük mindkét oldalát.\n3. Ízlés szerint fogyaszthatjuk mézzel, mogyorókrémmel, olvasztott csokival, lekvárral, juharsziruppal.', 'amerikaiPalacsinta.jpg', 'https://www.nosalty.hu/recept/gyors-amerikai-palacsinta'),
(14, 'főétel', 'Paprikás krumpli', 'krumpli;sós', 40, 4, '{\"hagyma\":\"2 fej\",\"olaj\":\"főzéshez\",\"kolbász\":\"20 dkg\",\"pirospaprika\":\"2 evőkanál\",\"burgonya\":\"1 kg\",\"só\":\"ízlésre\",\"paradicsompüré\":\"1 evőkanál\"}', '1. A hagyományos paprikás krumpli elkészítéséhez a hagymát megtisztítjuk, apró kockára vágjuk.\n2. Tűzálló tálban egy kevés olajat forrósítunk, beletesszük a felaprított hagymát, és üvegesre pirítjuk, majd hozzáadjuk a felkarikázott kolbászt, és megpirítjuk.\n3. Lehúzzuk a lábast a tűzhelyről, megszórjuk a kolbászos pirított hagymát a pirospaprikával.\n4. Átkeverjük, majd hozzáadjuk az alaposan megmosott, megtisztított, kockákra vágott burgonyát.\n5. Felöntjük annyi vízzel, ami majdnem ellepi. Megsózzuk, hozzáadjuk a paradicsompürét, és addig főzzük, amíg a burgonya megpuhul.\n6. Friss kenyérrel, savanyú uborkával tálaljuk.', 'paprikasKrumpli.jpg', 'https://www.mindmegette.hu/recept/paprikas-krumpli'),
(15, 'főétel', 'Csőben sült karalábé', 'vegetáriánus', 45, 4, '{\"karalábé\":\"4 db (200 g/db)\",\"vaj\":\"100 g\",\"vöröshagyma\":\"2 fej\",\"fokhagyma\":\"6 gerezd\",\"cukor\":\"2 teáskanál (kristálycukor)\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"bazsalikom\":\"0.5 csokor\",\"finomliszt\":\"35 g\",\"tej\":\"500 ml\",\"szerecsendió\":\"0.5 teáskanál (őrölt)\",\"edami sajt\":\"150 g\",\"petrezselyem\":\"0.5 csokor\"}', '1. A karalábékat megpucoljuk és 1 cm-es szeletekre vágjuk, majd bő, enyhén sós vízben előfőzzük őket kb. 10 perc alatt. Akkor jó, ha marad egy kis roppanása a zöldségnek. Leszűrjük és félretesszük. \n2. Egy serpenyőben, közepesen magas hőfokon megkaramellizáljuk a vajon (50 g) a félfőre vágott vöröshagymát és a szeletelt fokhagymát a cukorral kb. 10 perc alatt, közben sózzuk és borsozzuk, majd ha elkészültünk, belekeverjük a finomra vágott bazsalikomot és félrerakjuk. \n3. A besamelhez közepesen magas hőfokon, egy lábasban habzásig melegítjük a vajat (50 g), majd ráöntjük a lisztet és 1 percig pirítjuk. Felöntjük a hideg tejjel, amit egy habverővel folyamatosan keverünk, közben sózzuk, borsozzuk és ízesítjük a szerecsendióval. Forrástól számítva 2-3 percig főzzük a besamelt, majd lehúzzuk a tűzről. \n4. Egy tepsibe rétegezzük félig fedve a karalábészeleteket, az egészet beborítjuk a pirított vajas, bazsalikomos hagymával, és leöntjük a besamellel. A tetejére szórjuk a reszelt edami sajtot, és betesszük grill funkción a 230 fokra előmelegített sütőbe kb. 15 percre, míg a sajt szépen rápirul. Utána már szedhetjük is tányérra a csőben sült karalábét, amit megszórunk finomra vágott petrezselyemmel. ', 'csobenSultKaralabe.jpg', 'https://streetkitchen.hu/green-kitchen/vegetarianus/csoben-sult-karalabe/'),
(16, 'desszert', 'Körtés pite', 'édes', 110, 1, '{\"finomliszt\":\"300 g\",\"vaj\":\"150 g (fagyasztott)\",\"só\":\"1 csipet\",\"sütőpor\":\"1 teáskanál\",\"cukor\":\"180 g (porcukor)\",\"citrom\":\"1 db\",\"tojás\":\"2 db\",\"körte\":\"4 db\",\"mandulaszirom\":\"50 g\",\"vaníliás pudingpor\":\"1 csomag\",\"tej\":\"500 ml\"}', '1. A körtés pite elkészítését a tésztával kezdjük. Ehhez a lisztbe belereszeljük a vajat úgy, hogy közben néha belemártjuk a lisztbe. Ezzel a technikával nem fog összeállni egy csomóba a vaj. Beleszórjuk a sót és a sütőport, és hozzáadunk 130 g porcukrot, valamint a citrom lereszelt héját. Jöhet a tálba egy egész tojás és egy tojássárgája, majd az egész tésztát alaposan összegyúrjuk és folpackba csomagolva hűtőben pihentetjük legalább 30 percet. \n2. A citrom levét kifacsarjuk, a körtéket pedig megtisztítjuk és felcikkezzük. A körtecikkeket összekeverjük a citromlével és lefedve 200 fokra előmelegített sütőben 35 percig sütjük, majd félretesszük kihűlni. \n3. A pihentetett tésztát lisztezett felületen kb. 5 mm vastagon kinyújtjuk a piteformánál nagyobbra és belefektetjük a kivajazott formába úgy, hogy a széleinél a túllógó részt levágjuk. A leeső darabokat újra összegyúrjuk és félretesszük. A megmaradt tojásfehérjét lazán felverjük 1 evőkanál porcukorral, és beleforgatjuk a mandulaszirmot és a kihűlt körtecikkeket. Ezt a keveréket belesimítjuk a tésztával kibélelt piteformába. \n4. A pudingport kikeverjük kb. 100 ml tejjel, majd a maradék tejhez adjuk és folyamatosan kevergetve közepes lángon felforraljuk. A még meleg pudingot is a pitére simítjuk. Az újra összegyúrt tésztát kinyújtjuk, 2 cm-es csíkokra vágjuk és berácsozzuk vele a pite tetejét. 180 fokra előmelegített sütőben 35-40 perc alatt készre sütjük, majd szeletelés előtt legalább langyosra hűtjük és megszórjuk porcukorral. ', 'kortesPite.jpg', 'https://streetkitchen.hu/fantasztikus-desszertek/kortes-pite/'),
(17, 'egyéb', 'Mazsolás kalács', 'édes;kalács', 60, 3, '{\"liszt\":\"1 kg\",\"só\":\"1.2dkg\",\"cukor\":\"12dkg\",\"tojássárgája\":\"3 db\",\"tejszín\":\"400 ml\",\"friss élesztő\":\"4 dk\",\"mazsola\":\"8 dkg\",\"vanília kivonat\":\"2 kiskanál\"}', '1. A tejet, a tejszínt, az elmorzsolt élesztőt és a tojássárgákat elkevertetjük, majd hozzáadjuk az átszitált lisztet, a cukrot, a sót és a vaníliát és közepes fokozaton kidagasztatjuk a géppel.\n2. Ha erős a liszt, adhatunk még hozzá tejet. Ne legyen túl kemény, de túl lágy sem a tészta. Öt perc után adjuk hozzá a mazsolát és további két percet dagasszuk, majd meleg helyen, letakarva 45 percet érleljük a tésztát.\n3. Miután a kalácstészta megpihent, kilenc részre osztjuk, mert három, háromszálas kalácsot fogunk belőle készíteni. Ha elkészültünk a felosztással, felgömbölyítjük őket, aztán letakarva tovább pihentetjük a tésztát.\n4. Kivajazzuk a sütőformákat, a tésztákból a pihentetés után kalácsot fonunk. Ha ezzel is elkészültünk, betesszük a kalácsokat a sütőformába, majd a felvert tojásokkal megkenjük őket.\n5. Meleg helyen tovább kelesztjük a tésztákat (kb. 45 perc), közben pedig a sütőt alsó és felső sütési fokozatban 190 fok környékére melegítjük. Mielőtt bepakolnánk a kalácsokat a sütőbe, újra megkenjük vékonyan a tojások sárgájával, majd ezután 10 percig 190 fokon, majd lejjebb véve 170 fokra a hőmérsékletet, további 15-20 percig sütjük.', 'mazsolasKalacs.jpeg', 'https://www.mindmegette.hu/recept/mazsolas-kalacs'),
(18, 'főétel', 'Indiai vajas csirke', 'indiai;exotikus', 60, 4, '{\"joghurt\":\"200 g\",\"mustárolaj\":\"40  ml\",\"őrölt deggi csili\":\"20 g\",\"gyömbér-fokhagyma paszta\":\"80 g\",\"só\":\"8 g \",\"kömény\":\"20 g (őrölt)\",\"koriander\":\"20 g (őrölt)\",\"csirkemell\":\"800 g\",\"víz\":\"2 dl\",\"paradicsom\":\"1 kg\",\"vöröshagyma\":\"400 g\",\"kesudió\":\"320 g\",\"zöld kardamom\":\"4 g\",\"babérlevél\":\"4 g\",\"dinnyemag\":\"120 g\",\"fahéjrúd\":\"8 g\",\"olaj\":\"80 ml\",\"garam masala\":\"4 g\",\"fokhagymapaszta\":\"8 g\",\"méz\":\"40 g\",\"tejszín\":\"40 g\",\"vaj\":\"60 g\"}', '1. Pácolás: Egy tálba tegyük bele a felkockázott csirkemelleket. Keverjük össze a joghurtot, a mustárolajat, az őrölt deggi csilit, a sót, a gyömbéres fokhagymapasztát, az őrölt köményt és az őrölt koriandert. Alaposan dolgozzuk el a csirkén, és hűtőben lefedve, hagyjuk pihenni egy éjszakán át, hogy a fűszerek jól átjárják a húst.\n2. Mártás: Egy edényben forrósítsunk fel 2 liter vizet. Adjuk hozzá az apróra vágott vöröshagymát, a friss paradicsomot, a kesudiót, a zöld kardamomot, a babérlevelet, a dinnyemagot és a fahéjrudat. Forraljuk a mártást 2 órán keresztül, majd turmixoljuk össze a hozzávalókat. Turmixolás előtt a babérleveleket vegyük ki a mártásból, vagy használjuk őrölt formában.\n3. Befejezés: Egy másik serpenyőben hevítsünk olajat, majd adjunk hozzá gyömbéres fokhagymapasztát. Melegítsük fel, majd hagyjuk kihűlni. Következő lépésként adjunk hozzá őrölt köményt, őrölt koriandert, garam masalát, sót, kasoori methit, zöld kardamomport és mézet, majd keverjük össze mindezt a korábban elkészített mártással. Főzzük a mártást, amíg sűrű lesz, majd adjuk hozzá a sült csirkét, és hagyjuk forrni. Végül keverjünk tejszínt és vajat a mártásba.\n4. Tálalás: Szedjük a vajas csirkét a már­tással egy tálba, köretként kínáljunk hozzá rizst vagy indiai lepénykenyeret. Csirkemell helyett paneert is használhatunk, így vegetáriánus változatban is elkészíthetjük ezt az ételt.', 'indiaivajas.png', 'https://magyarkonyhaonline.hu/receptek/indiai-vajas-csirke-3'),
(19, 'desszert', 'Linzer', 'édes;olcsó;könnyű', 135, 8, '{\"liszt\":\"300 g\",\"vaj\":\"200 g\",\"porcukor\":\"100 g\",\"vaníliás cukor\":\"1 tasak\",\"citromhéj\":\"1 citromnyi\",\"tojás sárgája\":\"1 darab\",\"baracklekvár\":\"200 g\",\"só\":\"1 kiskanálnyi\",\"porcukor\":\"6 ek (szóráshoz)\"}', '1. A tésztához egy keverőtálban összekeverjük a lisztet, sót és a porcukrot. Kockázzuk bele a hideg vajat (vagy le is reszelhetjük), és morzsoljuk össze. Mehet hozzá a tojássárgája, vaníliás cukor és citromhéj is, ezekkel együtt gyors mozdulatokkal dolgozzuk össze, majd formázzunk belőle egy lapos cipót, és csomagoljuk be folpackba. Hűtőben pihentessük 30-40 percet (de akár egy egész éjszakát is hagyhatjuk).\n2. A sütőt előmelegítjük 180 fokra. Addig a tésztát kivesszük a hűtőből, és hagyjuk kicsit állni szobahőmérsékleten.\n3. Lisztezett gyúródeszkán 2-3 mm vékonyra kinyújtjuk, majd a klasszikus virág alakú formával kiszúrjuk. Kb. 50-60 darab jön ki. Ne feledjük a virágok tetejét, azoknak habcsővel szúrjuk ki a közepüket.\n4. A linzervirágokat tegyük sütőpapíros tepsire, és 12-15 perc alatt világos színűre sütjük. Világos színűnek kell maradnia, így lesz szép a végeredmény. Mialatt kihűl, még úgyis \"tovább sül\", úgyhogy nem lesz semmiképp sem nyers.\n5. Miután teljesen kihűltek, az aljakra nyomunk egy kávéskanálnyi lekvárt (habzsákból a leggyorsabb és legegyszerűbb). A tetejüket porcukrozzuk le, majd illesszük össze a lekváros aljakkal. Akkor lesz igazán jó ha egy napot áll, így kelően összepuhul.', 'linzer.jpg', 'https://www.nosalty.hu/recept/klasszikus-linzer-baracklekvarral'),
(20, 'főétel', 'Rakott krumpli', 'krumpli;sajtos', 90, 6, '{\"burgonya\":\"1.5 kg\",\"kolbász\":\"40 dkg\",\"tojás\":\"6 db\",\"tejföl\":\"3 dl\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"vaj\":\"2 evőkanál\",\"füstölt szalonna\":\"15 dkg\"}', '1. A burgonyát meghámozzuk, és kb. 5 mm vastag szeletekre vágjuk. A kolbászt karikákra vágjuk, a tojásokat keményre főzzük, majd karikákra vágjuk.\n2. Egy tepsit kivajazunk, és rétegezzük: burgonya, só, bors, kolbász, tojás, tejföl. Ismételjük a rétegezést, amíg elfogynak a hozzávalók. A legfelső réteg legyen burgonya, amit tejföllel lekenünk.\n3. A szalonnát apró kockákra vágjuk, és serpenyőben ropogósra sütjük, majd a rakott krumpli tetejére szórjuk.\n4. 180°C-ra előmelegített sütőben 1 órán át sütjük, amíg a burgonya megpuhul és a teteje aranybarna lesz.', 'rakottKrumpli.jpg', 'https://www.mindmegette.hu/recept/rakott-krumpli'),
(21, 'leves', 'Gulyásleves', 'hagyományos', 120, 8, '{\"marhalábszár\":\"1 kg\",\"vöröshagyma\":\"2 fej\",\"fokhagyma\":\"3 gerezd\",\"pirospaprika\":\"2 evőkanál\",\"őrölt kömény\":\"1 teáskanál\",\"burgonya\":\"50 dkg\",\"sárgarépa\":\"2 db\",\"paradicsompüré\":\"2 evőkanál\",\"zsír\":\"2 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"csipetke\":\"20 dkg\"}', '1. A hagymát apróra vágjuk, a zsíron üvegesre pirítjuk. Hozzáadjuk a fokhagymát, majd lehúzzuk a tűzről és belekeverjük a pirospaprikát.\n2. Hozzáadjuk a kockára vágott húst, és addig pirítjuk, amíg minden oldala fehér lesz. Felöntjük 2 liter vízzel, hozzáadjuk a köményt, sót, borsot és paradicsompürét.\n3. Fedő alatt lassú tűzön 1 órán át főzzük. Ezután hozzáadjuk a kockára vágott sárgarépát és burgonyát, majd további 30 percig főzzük.\n4. Közben elkészítjük a csipetkét: lisztből, tojásból és sóból gyúrunk kemény tésztát, majd csipkedjük a levesbe. 5 percig főzzük, majd tálaljuk.', 'gulyasleves.jpg', 'https://sobors.hu/receptek/gulyasleves-hazi-csipetkevel-recept/'),
(22, 'desszert', 'Somlói galuska', 'édes;klasszikus', 60, 6, '{\"liszt\":\"25 dkg\",\"tojás\":\"4 db\",\"cukor\":\"20 dkg\",\"sütőpor\":\"1 csomag\",\"tej\":\"2.5 dl\",\"rum\":\"2 evőkanál\",\"csokoládémáz\":\"15 dkg\",\"tejszín\":\"3 dl\",\"dió\":\"10 dkg\",\"vanília puding\":\"1 csomag\"}', '1. A tojások sárgáját a cukorral habosra keverjük. Hozzáadjuk a lisztet és sütőport, majd a tejet. A tojásfehérjéből kemény habot verünk, és óvatosan beleforgatjuk.\n2. A tésztát 3 részre osztjuk. Az egyik részbe kakaóporral, a másikba rummal ízesítünk. Mindhárom részt külön sütőpapírral bélelt tepsiben megsütjük 180°C-on 15 percig.\n3. A kihűlt piskótákat kockákra vágjuk. A vanília pudingot elkészítjük a tejjel és cukorral.\n4. Rétegezzük: piskóta, rumos szirup, puding, csokoládémáz, tejszínhab. Ismételjük a rétegeket, a tetejére diót szórunk.', 'somloiGaluska.jpg', 'https://www.mindmegette.hu/recept/somloi-galuska-az-eredeti-recept-alapjan'),
(23, 'reggeli', 'Lángos', 'sós;utcai', 90, 4, '{\"liszt\":\"50 dkg\",\"élesztő\":\"2 dkg\",\"tej\":\"2.5 dl\",\"só\":\"1 teáskanál\",\"cukor\":\"1 kávéskanál\",\"olaj\":\"a sütéshez\",\"tejföl\":\"tálaláshoz\",\"reszelt sajt\":\"tálaláshoz\",\"fokhagymás víz\":\"tálaláshoz\"}', '1. A tejben feloldjuk az élesztőt és a cukrot, majd hagyjuk 10 percet állni. A lisztbe keverjük a sót, majd hozzáadjuk az élesztős tejet és gyúrunk lágy tésztát.\n2. Letakarva meleg helyen 1 órán át kelesztjük.\n3. A tésztát kézzel kinyújtjuk, majd olajban bőven, mindkét oldalát aranybarnára sütjük.\n4. Melegen tálaljuk tejföllel, reszelt sajttal és fokhagymás vízzel.', 'langos.jpg', 'https://www.mindmegette.hu/recept/sajtos-tejfolos-langos-iii'),
(24, 'főétel', 'Töltött paprika', 'hagyományos', 90, 6, '{\"paprika\":\"12 db (töltő)\",\"darált hús\":\"50 dkg\",\"rizs\":\"15 dkg\",\"vöröshagyma\":\"2 fej\",\"fokhagyma\":\"3 gerezd\",\"pirospaprika\":\"1 evőkanál\",\"paradicsom\":\"1 kg\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"olaj\":\"2 evőkanál\"}', '1. A rizst félig megfőzzük. A hagymát apróra vágjuk, és az olajon üvegesre pirítjuk. Hozzáadjuk a fokhagymát és a pirospaprikát.\n2. A darált húst összekeverjük a rizzsel, hagymás keverékkel, sóval és borssal.\n3. A paprikák tetejét levágjuk, magházukat kitisztítjuk, majd megtöltjük a húsos keverékkel.\n4. Egy lábas aljára paradicsomszeleteket teszünk, ráhelyezzük a töltött paprikákat, és felöntjük vízzel. Fedő alatt 45 percig főzzük.', 'toltottPaprika.jpg', 'https://www.mindmegette.hu/recept/a-legfinomabb-toltott-paprika'),
(25, 'főétel', 'Kínai szezámmagos csirke', 'kínai;csirke', 30, 4, '{\"csirkemell\":\"60 dkg\",\"szójaszósz\":\"5 evőkanál\",\"méz\":\"2 evőkanál\",\"fokhagyma\":\"3 gerezd\",\"gyömbér\":\"2 cm\",\"szezámolaj\":\"1 evőkanál\",\"kukoricaliszt\":\"2 evőkanál\",\"szezámmag\":\"2 evőkanál\",\"olaj\":\"sütéshez\",\"rizs\":\"körethez\"}', '1. A csirkemellet kockára vágjuk. A szójaszószt, mézet, összezúzott fokhagymát és reszelt gyömbért összekeverjük, majd a húst belemártjuk és 30 percre beáztatjuk.\n2. A kukoricalisztbe forgatjuk a csirkedarabokat, majd bő forró olajban aranybarnára sütjük.\n3. A maradék mártást felmelegítjük, és a sült csirkére öntjük. Szezámmaggal megszórva tálaljuk, rizzsel.', 'kinaiSzezammagosCsirke.jpg', 'https://www.nosalty.hu/recept/kinai-omlos-szezammagos-csirke-zoldseges-piritott-tesztaval'),
(26, 'leves', 'Paradicsomleves', 'leves;nyári', 40, 6, '{\"paradicsom\":\"1.5 kg\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"2 gerezd\",\"olivaolaj\":\"2 evőkanál\",\"bazsalikom\":\"1 csokor\",\"cukor\":\"1 teáskanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"tejszín\":\"2 dl\",\"zsemlemorzsa\":\"tálaláshoz\"}', '1. A paradicsomokat megmossuk, negyedeljük. A hagymát és fokhagymát apróra vágjuk.\n2. Az olajon megdinszteljük a hagymát, hozzáadjuk a paradicsomot és a fűszereket. 20 percig főzzük.\n3. Turmixoljuk, majd szitán áttörjük. Hozzáadjuk a tejszínt, a megfőzött tésztát, és újra felmelegítjük. Petrezselyemmel tálaljuk.', 'paradicsomleves.jpg', 'https://www.nosalty.hu/recept/menzas-paradicsomleves-betutesztaval'),
(27, 'reggeli', 'Gofri', 'édes;reggeli', 25, 4, '{\"liszt\":\"25 dkg\",\"tojás\":\"2 db\",\"tej\":\"3 dl\",\"vaj\":\"5 dkg\",\"sütőpor\":\"1 csomag\",\"cukor\":\"2 evőkanál\",\"só\":\"1 csipet\",\"vanília\":\"1 csomag\"}', '1. A lisztet elkeverjük a sütőporral, cukorral és sóval.\n2. A tojásokat, olvasztott vajat és tejet hozzáadjuk, simára keverjük.\n3. A gofrisütőt felmelegítjük, vékonyan kiolajozzuk, és a tésztából adagonként sütjük a gofrit 3-4 percig. Tetszés szerint lekvárosan, csokival vagy gyümölccsel tálaljuk.', 'gofri.jpg', 'https://www.nosalty.hu/recept/alap-gofri'),
(28, 'desszert', 'Lekváros bukta', 'édes;sütemény', 90, 12, '{\"liszt\":\"50 dkg\",\"élesztő\":\"2 dkg\",\"tej\":\"2 dl\",\"tojás\":\"1 db\",\"vaj\":\"10 dkg\",\"cukor\":\"10 dkg\",\"só\":\"1 csipet\",\"baracklekvár\":\"40 dkg\",\"porcukor\":\"díszítéshez\"}', '1. A meleg tejbe belemorzsoljuk az élesztőt, cukrot és egy csipet lisztet, majd kelni hagyjuk.\n2. A lisztbe keverjük a tojást, olvasztott vajat, sót és a felfuttatott élesztőt. Lágy tésztát gyúrunk, és kelni hagyjuk.\n3. A tésztát kinyújtjuk, négyzet alakúra vágjuk, mindegyikbe teszünk egy kis lekvárt, és összehajtjuk.\n4. 180°C-ra előmelegített sütőben 25 percig sütjük. Porcukorral megszórva tálaljuk.', 'lekvarosBukta.jpg', 'https://www.mindmegette.hu/recept/lekvaros-bukta'),
(29, 'reggeli', 'Baconbe tekert virsli', 'sós;reggeli', 20, 4, '{\"virsli\":\"8 db\",\"bacon\":\"16 szelet\",\"mustár\":\"ízlésre\",\"ketchup\":\"ízlésre\"}', '1. Minden virslit 2 szelet baconbe csavarunk.\n2. Serpenyőben vagy grillen mindkét oldalát aranybarnára sütjük.\n3. Mustárral és ketchuppal tálaljuk friss kenyérrel vagy zsemlével.', 'baconbeTekertVirsli.jpg', 'https://streetkitchen.hu/otthon/baconbe-tekert-virsli/'),
(30, 'főétel', 'Pirosrántásos borsó főzelék', 'vegetáriánus;főzelék', 45, 4, '{\"zöldborsó\":\"80 dkg (friss vagy fagyasztott)\",\"vöröshagyma\":\"1 fej\",\"liszt\":\"2 evőkanál\",\"pirospaprika\":\"1 evőkanál\",\"só\":\"ízlésre\",\"cukor\":\"1 kávéskanál\",\"tejföl\":\"2 dl\",\"olaj\":\"2 evőkanál\"}', '1. A hagymát apróra vágjuk, az olajon üvegesre pirítjuk. Hozzáadjuk a pirospaprikát és a lisztet, és rántást készítünk.\n2. Felöntjük vízzel, hozzáadjuk a borsót, és puhára főzzük.\n3. Sóval, cukorral ízesítjük, végül a tejföllel behabarjuk. Tojással vagy sült kolbásszal tálaljuk.', 'pirosrantasosBorsoFozelek.jpg', 'https://www.nosalty.hu/recept/pirosrantasos-borso-fozelek'),
(31, 'desszert', 'Rákóczi túrós', 'édes;sütemény', 60, 12, '{\"liszt\":\"30 dkg\",\"vaj\":\"20 dkg\",\"tojás\":\"1 db\",\"cukor\":\"10 dkg\",\"sütőpor\":\"1 csomag\",\"túró\":\"40 dkg\",\"vaníliás cukor\":\"1 csomag\",\"baracklekvár\":\"20 dkg\",\"tejföl\":\"2 dl\"}', '1. A lisztet összegyúrjuk a vajjal, tojással, 5 dkg cukorral és sütőporral. Kinyújtjuk, és tepsibe helyezzük.\n2. A túrót összekeverjük a tejföllel, maradék cukorral és vaníliás cukorral, rákenjük a tésztára.\n3. 180°C-ra előmelegített sütőben 30 percig sütjük. Kihűlés után lekváros csíkokat rácsot formálva kenünk rá.', 'rakocziTuros.jpg', 'https://www.mindmegette.hu/recept/rakoczi-turos'),
(32, 'főétel', 'Hortobágyi húsos palacsinta', 'hagyományos', 60, 6, '{\"darált sertéshús\":\"50 dkg\",\"vöröshagyma\":\"1 fej\",\"pirospaprika\":\"1 evőkanál\",\"liszt\":\"20 dkg\",\"tojás\":\"2 db\",\"tej\":\"5 dl\",\"só\":\"ízlésre\",\"tejföl\":\"3 dl\"}', '1. A hagymát apróra vágjuk, a hússal együtt megpirítjuk. Piros paprikával ízesítjük.\n2. A palacsintatésztát elkészítjük, és vékony palacsintákat sütünk.\n3. A húsos tölteléket a palacsintákba tekerve, tepsibe helyezzük, tejföllel leöntjük, és 180°C-on 20 percig sütjük.', 'hortobagyiHusosPalacsinta.jpg', 'https://www.nosalty.hu/recept/hortobagyi-husos-palacsinta'),
(33, 'leves', 'Jókai bableves', 'hagyományos', 180, 8, '{\"bab\":\"40 dkg (száraz)\",\"füstölt csülök\":\"1 kg\",\"vöröshagyma\":\"2 fej\",\"sárgarépa\":\"2 db\",\"zeller\":\"1 db\",\"paradicsompüré\":\"2 evőkanál\",\"fokhagyma\":\"3 gerezd\",\"pirospaprika\":\"1 evőkanál\",\"liszt\":\"1 evőkanál\",\"só\":\"ízlésre\"}', '1. A babot előző este beáztatjuk. Másnap a csülköt és a babot puhára főzzük.\n2. A zöldségeket apróra vágjuk, a hagymát megpirítjuk, hozzáadjuk a paprikát és paradicsompürét.\n3. A főzőléből egy keveset kiveszünk, a liszttel elkeverjük, majd visszaöntjük a levesbe. Főzzük még 10 percig.', 'jokaiBableves.jpg', 'https://www.mindmegette.hu/recept/jokai-bableves'),
(34, 'főétel', 'Töltött káposzta', 'hagyományos', 180, 8, '{\"savanyú káposzta\":\"2 kg\",\"darált hús\":\"80 dkg\",\"rizs\":\"15 dkg\",\"füstölt szalonna\":\"20 dkg\",\"tejföl\":\"3 dl\",\"pirospaprika\":\"1 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\"}', '1. A rizst félig megfőzzük, és összekeverjük a darált hússal, sóval, borssal.\n2. A káposztaleveleket megtöltjük a húsos keverékkel, és szorosan feltekerjük.\n3. Egy lábas aljára káposztát teszünk, rá a töltelékeket, és rétegezve végig. Felöntjük vízzel, és lassú tűzön 2 órán át főzzük.\n4. Tejföllel és pirospaprikával tálaljuk.', 'toltottKaposzta.jpg', 'https://sobors.hu/technologia/igy-keszul-a-tokeletes-toltott-kaposzta/'),
(35, 'reggeli', 'Francia pirítós', 'reggeli;édes', 15, 2, '{\"kenyér\":\"4 szelet\",\"tojás\":\"2 db\",\"tej\":\"1 dl\",\"cukor\":\"2 evőkanál\",\"vanília\":\"1 csomag\",\"vaj\":\"sütéshez\",\"porcukor\":\"díszítéshez\"}', '1. A tojásokat felverjük a tejjel, cukorral és vaníliával.\n2. A kenyérszeleteket belemártjuk a keverékbe, majd vajon mindkét oldalát aranybarnára sütjük.\n3. Porcukorral megszórva, gyümölccsel vagy mézzel tálaljuk.', 'franciaPiritos.jpg', 'https://www.nosalty.hu/recept/francia-piritos'),
(36, 'desszert', 'Rigó Jancsi', 'édes;csokoládés', 120, 12, '{\"tojás\":\"6 db\",\"cukor\":\"30 dkg\",\"liszt\":\"15 dkg\",\"kakaópor\":\"3 evőkanál\",\"csokoládé\":\"30 dkg\",\"tejszín\":\"4 dl\",\"vanília\":\"1 rúd\"}', '1. A tojások sárgáját a cukor felével habosra keverjük, hozzáadjuk a lisztet és kakaóport.\n2. A fehérjéből kemény habot verünk a maradék cukorral, és óvatosan a masszába keverjük.\n3. Tepsiben 180°C-on 15 percig sütjük. Kihűtjük, majd két részre vágjuk.\n4. A csokoládét a tejszínnel és a vaníliával gőz felett olvasztjuk, majd a piskóta rétegek közé kenjük. Hűtőben dermesztjük.', 'rigoJancsi.jpg', 'https://femina.hu/recept/rigojancsi-suti/'),
(37, 'főétel', 'Brassói aprópecsenye', 'hús;sült', 90, 6, '{\"sertéslapocka\":\"1.5 kg\",\"burgonya\":\"1 kg\",\"fokhagyma\":\"6 gerezd\",\"zsír\":\"sütéshez\",\"majoránna\":\"1 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\"}', '1. A húst kockára vágjuk, sózzuk, borsozzuk, majoránnával megszórjuk.\n2. A burgonyát meghámozzuk, és nagyobb kockákra vágjuk.\n3. Forró zsírban először a húst pirítjuk meg, majd hozzáadjuk a burgonyát és a fokhagymát. Addig sütjük, amíg minden aranybarna és ropogós lesz.', 'brassoiaAropecsenye.jpg', 'https://www.kukkoniashop.sk/hu/brassoi-apropecsenye'),
(38, 'leves', 'Halászlé', 'hagyományos;hal', 120, 8, '{\"ponty\":\"2 kg\",\"vöröshagyma\":\"3 fej\",\"pirospaprika\":\"5 evőkanál\",\"só\":\"ízlésre\",\"erős paprika\":\"ízlésre\",\"víz\":\"3 l\"}', '1. A halat megtisztítjuk, a fejét és a csontját vízbe tesszük, és 1 órán át főzzük.\n2. A hagymát apróra vágjuk, a paprikával együtt a lébe tesszük, és további 30 percig főzzük.\n3. A halhúst nagyobb darabokban visszatesszük a levesbe, és 5 percig főzzük. Erős paprikával ízesítjük.', 'halaszle.jpg', 'https://www.mindmegette.hu/recept/halaszle'),
(39, 'desszert', 'Krémes', 'édes;réteges', 180, 12, '{\"liszt\":\"40 dkg\",\"vaj\":\"25 dkg\",\"tojás\":\"1 db\",\"sütőpor\":\"1 csomag\",\"tej\":\"1 l\",\"vanília puding\":\"2 csomag\",\"cukor\":\"30 dkg\",\"csokoládé\":\"20 dkg\"}', '1. A lisztet összegyúrjuk a vajjal, tojással és sütőporral. Kinyújtjuk, és tepsiben 180°C-on 15 percig sütjük.\n2. A pudingot a tejjel és cukorral főzzük, majd kihűtjük.\n3. A piskóta tetejére kenjük a pudingot, majd a felolvasztott csokoládét öntjük rá. Hűtőben dermesztjük.', 'kremes.jpg', 'https://www.mindmegette.hu/recept/kremes'),
(40, 'főétel', 'Rántott sajt', 'sajtos;sült', 20, 4, '{\"trapista sajt\":\"40 dkg\",\"liszt\":\"10 dkg\",\"tojás\":\"2 db\",\"zsemlemorzsa\":\"20 dkg\",\"olaj\":\"sütéshez\",\"só\":\"ízlésre\"}', '1. A sajtot ujjnyi vastag szeletekre vágjuk.\n2. A lisztbe, felvert tojásba, majd zsemlemorzsába forgatjuk.\n3. Forró olajban mindkét oldalát aranybarnára sütjük. Salátával és tartármártással tálaljuk.', 'rantottSajt.jpg', 'https://www.nosalty.hu/recept/rantott-sajt'),
(41, 'leves', 'Újházi tyúkhúsleves', 'hagyományos', 180, 8, '{\"tyúk\":\"1 db\",\"sárgarépa\":\"3 db\",\"zeller\":\"1 db\",\"petrezselyemgyökér\":\"1 db\",\"vöröshagyma\":\"1 fej\",\"zöldborsó\":\"20 dkg\",\"só\":\"ízlésre\",\"tészta\":\"leveshez\"}', '1. A tyúkot nagy fazékban feltétlen vízzel lefedjük, és lassú tűzön főzzük.\n2. Hozzáadjuk a megtisztított, nagyobb darabokra vágott zöldségeket, és további 2 órát főzzük.\n3. A zöldségeket és a húst kivesszük, a levét leszűrjük. Tésztát főzünk bele, és a visszaaprított hússal és zöldségekkel tálaljuk.', 'ujhaziTyukhusleves.jpg', 'https://www.mindmegette.hu/recept/ujhazi-tyukhusleves'),
(42, 'desszert', 'Isler', 'édes;sütemény', 90, 24, '{\"liszt\":\"40 dkg\",\"vaj\":\"25 dkg\",\"tojás\":\"1 db\",\"cukor\":\"15 dkg\",\"lekvár\":\"20 dkg\",\"csokoládé\":\"20 dkg\",\"tej\":\"2 dl\"}', '1. A lisztet összegyúrjuk a vajjal, tojással és cukorral. 30 percig hűtőben pihentetjük.\n2. Kinyújtjuk, kiszúrjuk, és 180°C-on 10 percig sütjük.\n3. Kihűlés után lekvárosan összeragasztjuk, és csokoládémázzal leöntjük.', 'isler.jpg', 'https://www.mindmegette.hu/recept/isler'),
(43, 'főétel', 'Mákos tészta', 'édes;tészta', 30, 6, '{\"tészta\":\"50 dkg\",\"mák\":\"20 dkg\",\"cukor\":\"15 dkg\",\"tej\":\"3 dl\",\"vanília\":\"1 rúd\",\"vaj\":\"5 dkg\"}', '1. A tésztát sós vízben kifőzzük.\n2. A mákot a tejjel és a vaníliával felforraljuk, majd hozzáadjuk a cukrot.\n3. A leszűrt tésztát a mákos keverékkel összeragasztjuk, és vajjal ízesítjük.', 'makosTeszta.jpg', 'https://www.nosalty.hu/recept/makos-teszta'),
(44, 'desszert', 'Shrekszelet', 'édes;zöld;sütemény', 60, 12, '{\"liszt\":\"30 dkg\",\"cukor\":\"20 dkg\",\"tojás\":\"4 db\",\"zsír\":\"20 dkg\",\"kakaó\":\"2 evőkanál\",\"sütőpor\":\"1 csomag\",\"tej\":\"2 dl\",\"zöld ételfesték\":\"1 csomag\",\"vanília\":\"1 rúd\"}', '1. A tojásokat a cukorral habosra keverjük. Hozzáadjuk az olvasztott zsírt, majd a lisztet, kakaót és sütőport.\n2. A tésztát zöldre festjük, majd sütőpapírral bélelt tepsiben 180°C-on 25 percig sütjük.\n3. Kihűtés után kockákra vágjuk. Tálalás előtt porcukorral megszórjuk.', 'shrekszelet.jpg', 'https://www.nosalty.hu/recept/shrek-szelet'),
(45, 'desszert', 'Piskóta tekercs', 'sós;sütemény', 45, 8, '{\"liszt\":\"40 dkg\",\"tejföl\":\"2 dl\",\"vaj\":\"15 dkg\",\"só\":\"1 kávéskanál\",\"sütőpor\":\"1/2 csomag\",\"túró\":\"40 dkg\",\"tojás\":\"1 db\",\"fokhagyma\":\"2 gerezd\",\"snidling\":\"1 csokor\"}', '1. A lisztet összegyúrjuk a tejföllel, vajjal, sóval és sütőporral.\n2. A túrót összekeverjük a tojással, zúzott fokhagymával és finomra vágott snidlinggel.\n3. A tésztát kinyújtjuk, rákenjük a túrós tölteléket, feltekerjük.\n4. 180°C-ra előmelegített sütőben 30 percig sütjük. Melegen szeleteljük.', 'piskotaTekercs.jpg', 'https://www.mindmegette.hu/recept/tejfolos-poskota-tekercs'),
(46, 'desszert', 'Mézeskalács', 'édes;karácsonyi', 120, 30, '{\"liszt\":\"50 dkg\",\"méz\":\"20 dkg\",\"cukor\":\"10 dkg\",\"vaj\":\"10 dkg\",\"tojás\":\"1 db\",\"szódabikarbóna\":\"1 kávéskanál\",\"fahéj\":\"1 teáskanál\",\"szegfűszeg\":\"1/2 teáskanál\",\"gyömbér\":\"1/2 teáskanál\"}', '1. A mézet, cukrot és vajat felmelegítjük, majd hozzáadjuk a fűszereket.\n2. Kihűlés után hozzáadjuk a tojást és a lisztet szódabikarbónával.\n3. A tésztát fóliába csomagolva 1 éjszakára hűtőbe tesszük.\n4. Kinyújtjuk, kiszúrjuk, és 180°C-on 8-10 percig sütjük.', 'mezeskalacs.jpg', 'https://www.mindmegette.hu/recept/klasszikus-mezeskalacs'),
(47, 'főétel', 'Lencsefőzelék', 'vegetáriánus;főzelék', 60, 4, '{\"lencse\":\"40 dkg\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"2 gerezd\",\"pirospaprika\":\"1 evőkanál\",\"liszt\":\"1 evőkanál\",\"olaj\":\"2 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"ecet\":\"1 evőkanál\"}', '1. A lencsét megmossuk, és puhára főzzük.\n2. A hagymát apróra vágjuk, az olajon megpirítjuk, hozzáadjuk a pirospaprikát és lisztet, rántást készítünk.\n3. A lencséhez adjuk a rántást, és pár percig együtt főzzük. Ecettel ízesítjük. Tojással tálaljuk.', 'lencsefozelek.jpg', 'https://www.nosalty.hu/recept/lencsefozelek'),
(48, 'desszert', 'Kakaós csiga', 'édes;sütemény', 90, 12, '{\"liszt\":\"50 dkg\",\"tej\":\"2.5 dl\",\"élesztő\":\"2 dkg\",\"cukor\":\"10 dkg\",\"só\":\"1 csipet\",\"vaj\":\"5 dkg\",\"kakaópor\":\"10 dkg\",\"porcukor\":\"10 dkg\"}', '1. Az élesztőt a meleg tejben felfuttatjuk.\n2. A lisztet összegyúrjuk a cukorral, sóval, vajjal és az élesztős tejjel. Kelni hagyjuk.\n3. A tésztát kinyújtjuk, megszórjuk kakaóval és cukorral, feltekerjük.\n4. Szeletekre vágva, 180°C-on 20 percig sütjük.', 'kakaosCsiga.jpg', 'https://www.mindmegette.hu/recept/legjobb-kakaos-csiga'),
(49, 'főétel', 'Rakott káposzta', 'hagyományos;sült', 120, 8, '{\"savanyú káposzta\":\"1.5 kg\",\"darált hús\":\"50 dkg\",\"rizs\":\"15 dkg\",\"tejföl\":\"3 dl\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"füstölt szalonna\":\"15 dkg\"}', '1. A rizst félig megfőzzük, és összekeverjük a darált hússal, sóval és borssal.\n2. Tepsibe rétegezzük a káposztát, a húsos rizst és a tejfölt. Ismételjük a rétegezést.\n3. A szalonnát kockára vágjuk, és a tetejére szórjuk.\n4. 180°C-on 1 órán át sütjük.', 'rakottKaposzta.jpg', 'https://www.nosalty.hu/recept/rakott-kaposzta'),
(50, 'desszert', 'Kürtőskalács', 'édes;utcai', 60, 6, '{\"liszt\":\"50 dkg\",\"cukor\":\"15 dkg\",\"tojás\":\"2 db\",\"vaj\":\"10 dkg\",\"tej\":\"1.5 dl\",\"élesztő\":\"2 dkg\",\"só\":\"1 csipet\",\"fahéj\":\"2 evőkanál\"}', '1. Az élesztőt a meleg tejben felfuttatjuk.\n2. A lisztet összegyúrjuk a tojással, olvasztott vajjal, cukorral és az élesztős tejjel.\n3. A tésztát fél órára kelni hagyjuk.\n4. Kürtőskalács formára tekerve, forró sütőben vagy nyílt tűzön sütjük. Forrón fahéjas cukorba forgatjuk.', 'kurtoskalacs.jpg', 'https://www.mindmegette.hu/recept/eredeti-kurtoskalacs'),
(51, 'főétel', 'Rakott karfiol', 'vegetáriánus;sült', 60, 6, '{\"karfiol\":\"1 kg\",\"tejföl\":\"3 dl\",\"tojás\":\"3 db\",\"reszelt sajt\":\"20 dkg\",\"vaj\":\"2 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\"}', '1. A karfiolt rózsáira szedjük, és sós vízben puhára főzzük.\n2. A tojásokat keményre főzzük, és karikákra vágjuk.\n3. Tepsibe rétegezzük a karfiolt, tojást, tejfölt, megszórjuk sajttal. Ismételjük a rétegezést.\n4. 180°C-on 25 percig sütjük, amíg a teteje megpirul.', 'rakottKarfiol.jpg', 'https://www.nosalty.hu/recept/rakott-karfiol'),
(52, 'desszert', 'Túrógombóc', 'édes;túrós', 45, 8, '{\"túró\":\"50 dkg\",\"tojás\":\"1 db\",\"semmelknödel\":\"10 dkg\",\"só\":\"1 csipet\",\"vaj\":\"2 evőkanál\",\"zsemlemorzsa\":\"10 dkg\",\"porcukor\":\"tálaláshoz\"}', '1. A túrót áttörjük, összekeverjük a tojással, sóval és a felaprított knödellel.\n2. Gombócokat formázunk, és forró vízben kb. 8 percig főzzük, amíg feljönnek a víz tetejére.\n3. A vajon megpirítjuk a zsemlemorzsát, és a kész gombócokat megforgatjuk benne. Porcukorral megszórva tálaljuk.', 'turogomboc.jpg', 'https://www.mindmegette.hu/recept/turogomboc'),
(53, 'főétel', 'Császármorzsa', 'édes;reggeli', 20, 4, '{\"zsemlemorzsa\":\"30 dkg\",\"vaj\":\"10 dkg\",\"cukor\":\"10 dkg\",\"vaníliás cukor\":\"1 csomag\",\"tej\":\"tálaláshoz\"}', '1. A vajat serpenyőben felolvasztjuk, hozzáadjuk a zsemlemorzsát, és állandó keverés közben aranybarnára pirítjuk.\n2. Hozzáadjuk a cukrot és vaníliás cukrot, és még 1-2 percig pirítjuk.\n3. Melegen tálaljuk, tejjel öntve vagy gyümölccsel.', 'csaszarmorzsa.jpg', 'https://www.nosalty.hu/recept/csaszarmorzsa'),
(54, 'desszert', 'Bejgli', 'édes;karácsonyi', 180, 2, '{\"liszt\":\"50 dkg\",\"vaj\":\"25 dkg\",\"tojás\":\"2 db\",\"élesztő\":\"2 dkg\",\"tej\":\"1 dl\",\"cukor\":\"5 dkg\",\"dió vagy mák\":\"40 dkg\",\"méz\":\"2 evőkanál\"}', '1. Az élesztőt a meleg tejben felfuttatjuk.\n2. A lisztet összegyúrjuk a vajjal, tojással, cukorral és az élesztős tejjel. Pihentetjük.\n3. A diót/mákot összekeverjük a mézzel és kevés tejjel.\n4. A tésztát kinyújtjuk, rákenjük a tölteléket, feltekerjük. 180°C-on 40 percig sütjük.', 'bejgli.jpg', 'https://www.mindmegette.hu/recept/bejgli'),
(55, 'főétel', 'Rakott kelkáposzta', 'vegetáriánus;sült', 90, 6, '{\"kelkáposzta\":\"1 kg\",\"tejföl\":\"3 dl\",\"tojás\":\"3 db\",\"füstölt szalonna\":\"15 dkg\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"olaj\":\"2 evőkanál\"}', '1. A kelkáposztát megtisztítjuk, és sós vízben puhára főzzük.\n2. A szalonnát kockára vágjuk, és ropogósra sütjük.\n3. Tepsibe rétegezzük a káposztát, tejfölt, tojást és szalonnát. Ismételjük a rétegezést.\n4. 180°C-on 30 percig sütjük, amíg a teteje megpirul.', 'rakottKelkaposzta.jpg', 'https://www.nosalty.hu/recept/rakott-kelkaposzta'),
(56, 'desszert', 'Palacsinta', 'édes;reggeli', 30, 12, '{\"liszt\":\"30 dkg\",\"tojás\":\"3 db\",\"tej\":\"6 dl\",\"szénsavas víz\":\"2 dl\",\"só\":\"1 csipet\",\"olaj\":\"sütéshez\"}', '1. A lisztet a tojásokkal és egy kevés tejjel simára keverjük.\n2. Folyamatos keverés mellett hozzáadjuk a maradék tejet és a szénsavas vizet.\n3. Forró serpenyőben vékony palacsintákat sütünk mindkét oldalukon. Tetszés szerinti töltelékkel tálaljuk.', 'palacsinta.jpg', 'https://www.mindmegette.hu/recept/alap-palacsinta'),
(57, 'reggeli', 'Baconbetekert csirkemáj', 'húsimádó;sós', 20, 2, '{\"csirkemáj\":\"50 dkg\",\"tej\":\"5 dl \",\"fokhagyma\":\"2 gerezd\",\"babérlevél\":\"1 db\",\"rozmaring\":\"1 ág \",\"bacon\":\"15 dkg \",\"fehér bors\":\"1 tk\"}', '1. A májat hártyázzuk le, az ereket távolítsuk el, majd mossuk át folyó víz alatt.\n2. A tejet öntsük keverőtálba, majd adjuk hozzá a reszelt fokhagymát, borsot, babérlevelet és a rozmaringot. Ebbe pácoljuk bele a májakat, fedjük le, és egy éjszakára tegyük hűtőbe.\n3. Másnap a májakról itassuk fel a felesleges nedvességet, majd baconnel tekerjük körbe.\n4. A baconnel körbetekert májakat sorakoztassuk sütőpapírral bélelt tepsire, majd toljuk 180 fokosra előmelegített sütőbe, és 15-20 perc alatt süssük készre. (A sütési idő a máj méretétől és a sütőtől is függ, épp ezért előfordulhat, hogy picit tovább kell sütni.)\n5. Az elkészült baconnel körbetekert csirkemáj mellé kínálj krumplipürét vagy salátát.', 'baconbetekertCsirkemaj.jpg', 'https://sobors.hu/receptek/fokhagymas-baconnel-korbetekert-csirkemaj-recept/'),
(58, 'desszert', 'Almás pite', 'édes;gyümölcsös', 75, 8, '{\"liszt\":\"30 dkg\",\"vaj\":\"20 dkg\",\"cukor\":\"15 dkg\",\"tojás\":\"1 db\",\"sütőpor\":\"1 csomag\",\"alma\":\"1 kg\",\"fahéj\":\"1 teáskanál\",\"citromlé\":\"1 evőkanál\"}', '1. A lisztet összegyúrjuk a vajjal, cukorral, tojással és sütőporral.\n2. Az almát meghámozzuk, felkockázzuk, és a fahéjjal és citromlével összekeverjük.\n3. A tésztát két részre osztjuk, kinyújtjuk. Az egyik részt a tepsibe tesszük, rá az almát, majd a másik tésztarésszel lefedjük.\n4. 180°C-on 40 percig sütjük. Langyosra hűtve tálaljuk.', 'almasPite.jpg', 'https://www.mindmegette.hu/recept/almas-pite');
INSERT INTO `recept` (`id`, `tipus`, `nev`, `tagek`, `ido`, `adag`, `hozzavalok`, `elkeszites`, `kepnev`, `forras`) VALUES
(59, 'főétel', 'Túrós csusza', 'tészta;túrós', 30, 4, '{\"tészta\":\"40 dkg\",\"túró\":\"40 dkg\",\"tejföl\":\"2 dl\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"füstölt szalonna\":\"15 dkg\"}', '1. A tésztát sós vízben kifőzzük, leszűrjük.\n2. A szalonnát kockára vágjuk, és ropogósra sütjük.\n3. A tésztát összekeverjük a túróval, tejföllel, sóval és borssal.\n4. Tálaláskor a pirított szalonnával megszórjuk.', 'turosCsusza.jpg', 'https://www.nosalty.hu/recept/turos-csusza'),
(60, 'desszert', 'Kávés krémes', 'édes;krémes', 180, 12, '{\"liszt\":\"30 dkg\",\"vaj\":\"20 dkg\",\"tojás\":\"1 db\",\"sütőpor\":\"1 csomag\",\"tej\":\"1 l\",\"kávé\":\"5 evőkanál\",\"cukor\":\"30 dkg\",\"vanília puding\":\"2 csomag\"}', '1. A lisztet összegyúrjuk a vajjal, tojással és sütőporral. Kinyújtjuk, és tepsiben 180°C-on 15 percig sütjük.\n2. A pudingot a tejjel, cukorral és kávéval főzzük, majd kihűtjük.\n3. A piskóta tetejére kenjük a kávés pudingot, majd hűtőben dermesztjük.', 'kavesKremes.jpg', 'https://www.mindmegette.hu/recept/kaves-kremes'),
(61, 'főétel', 'Babfőzelék', 'vegetáriánus;főzelék', 60, 4, '{\"bab\":\"40 dkg\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"2 gerezd\",\"pirospaprika\":\"1 evőkanál\",\"liszt\":\"1 evőkanál\",\"olaj\":\"2 evőkanál\",\"só\":\"ízlésre\",\"ecet\":\"1 evőkanál\"}', '1. A babot megmossuk, és puhára főzzük.\n2. A hagymát apróra vágjuk, az olajon megpirítjuk, hozzáadjuk a pirospaprikát és lisztet, rántást készítünk.\n3. A babhoz adjuk a rántást, és pár percig együtt főzzük. Ecettel ízesítjük. Tojással tálaljuk.', 'babfozelek.jpg', 'https://www.nosalty.hu/recept/babfozelek'),
(62, 'desszert', 'Mákos guba', 'édes;mákos', 60, 6, '{\"zsemle\":\"6 db\",\"tej\":\"1 l\",\"mák\":\"20 dkg\",\"cukor\":\"15 dkg\",\"vanília\":\"1 rúd\",\"vaj\":\"5 dkg\"}', '1. A zsemléket kockára vágjuk, és a forró tejbe áztatjuk.\n2. A mákot a cukorral és a vaníliával összekeverjük.\n3. A zsemlekockákat összekeverjük a mákos keverékkel, és vajjal meglocsoljuk.\n4. 180°C-os sütőben 20 percig melegítjük.', 'makosGuba.jpg', 'https://www.mindmegette.hu/recept/makos-guba'),
(63, 'főétel', 'Rakott tészta', 'tészta;sajtos', 60, 6, '{\"tészta\":\"50 dkg\",\"tejföl\":\"3 dl\",\"tojás\":\"4 db\",\"sajt\":\"30 dkg\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"vaj\":\"2 evőkanál\"}', '1. A tésztát sós vízben kifőzzük, leszűrjük.\n2. A tojásokat keményre főzzük, és karikákra vágjuk.\n3. Tepsibe rétegezzük a tésztát, tejfölt, tojást és reszelt sajtot. Ismételjük a rétegezést.\n4. 180°C-on 25 percig sütjük, amíg a teteje megpirul.', 'rakottTeszta.jpg', 'https://www.nosalty.hu/recept/rakott-teszta'),
(64, 'desszert', 'Meggyes lepény', 'édes;gyümölcsös', 60, 8, '{\"liszt\":\"30 dkg\",\"vaj\":\"20 dkg\",\"cukor\":\"15 dkg\",\"tojás\":\"1 db\",\"sütőpor\":\"1 csomag\",\"meggy\":\"50 dkg\",\"porcukor\":\"díszítéshez\"}', '1. A lisztet összegyúrjuk a vajjal, cukorral, tojással és sütőporral.\n2. A tésztát kinyújtjuk, és tepsibe helyezzük.\n3. A meggyet a tésztára helyezzük, és 180°C-on 30 percig sütjük.\n4. Kihűlés után porcukorral megszórjuk.', 'meggyesLepeny.jpg', 'https://www.mindmegette.hu/recept/meggyes-lepeny'),
(65, 'főétel', 'Spenótfőzelék', 'vegetáriánus;főzelék', 45, 4, '{\"spenót\":\"1 kg\",\"vöröshagyma\":\"1 fej\",\"liszt\":\"1 evőkanál\",\"tejföl\":\"2 dl\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"olaj\":\"2 evőkanál\"}', '1. A spenótot megmossuk, és sós vízben puhára főzzük.\n2. A hagymát apróra vágjuk, az olajon megpirítjuk, hozzáadjuk a lisztet, rántást készítünk.\n3. A spenóthoz adjuk a rántást és a tejfölt, és pár percig együtt főzzük. Tojással tálaljuk.', 'spenotfozelek.jpg', 'https://www.nosalty.hu/recept/spenotfozelek'),
(66, 'desszert', 'Kókuszgolyó', 'édes;keksz', 30, 20, '{\"keksz\":\"40 dkg\",\"vaj\":\"10 dkg\",\"cukor\":\"10 dkg\",\"kakaó\":\"2 evőkanál\",\"kókuszreszelék\":\"10 dkg\",\"tej\":\"1 dl\"}', '1. A kekszet összetörjük, és összekeverjük a puha vajjal, cukorral, kakaóval és tejjel.\n2. Golyókat formázunk a masszából, és kókuszreszelékben meghempergetjük.\n3. Hűtőben dermesztjük.', 'kokuszgolyo.jpg', 'https://www.mindmegette.hu/recept/kokuszgolyo'),
(67, 'főétel', 'Tökfőzelék', 'vegetáriánus;főzelék', 50, 4, '{\"tök\":\"1 kg\",\"tejföl\":\"2 dl\",\"liszt\":\"1 evőkanál\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"2 gerezd\",\"só\":\"ízlésre\",\"cukor\":\"1 evőkanál\",\"olaj\":\"2 evőkanál\",\"pirospaprika\":\"1 teáskanál\"}', '1. A tököt meghámozzuk, magját eltávolítjuk, és kockára vágjuk.\n2. A hagymát apróra vágjuk, az olajon megpirítjuk, hozzáadjuk a pirospaprikát.\n3. Hozzáadjuk a tököt, kevés vizet öntünk alá, és puhára pároljuk.\n4. A lisztet a tejföllel elkeverjük, hozzáadjuk a főzelékhez, és összeforraljuk. Fokhagymával ízesítjük.', 'tokfozelek.jpg', 'https://www.nosalty.hu/recept/tokfozelek'),
(68, 'desszert', 'Csörögefánk', 'édes;sült', 60, 30, '{\"liszt\":\"50 dkg\",\"tojás\":\"3 db\",\"vaj\":\"10 dkg\",\"cukor\":\"10 dkg\",\"élesztő\":\"2 dkg\",\"tej\":\"2 dl\",\"só\":\"1 csipet\",\"citromhéj\":\"1 db\",\"olaj\":\"sütéshez\",\"porcukor\":\"díszítéshez\"}', '1. Az élesztőt a meleg tejben felfuttatjuk.\n2. A lisztet összegyúrjuk a tojásokkal, vajjal, cukorral, sóval, citromhéjjal és az élesztős tejjel.\n3. Kelni hagyjuk 1 órát.\n4. A tésztát kinyújtjuk, csíkokra vágjuk, és csavarod formát adunk.\n5. Forró olajban aranybarnára sütjük. Melegen porcukorral megszórjuk.', 'csorogefank.jpg', 'https://www.mindmegette.hu/recept/csorogefank'),
(69, 'főétel', 'Zöldborsófőzelék', 'vegetáriánus;főzelék', 45, 4, '{\"zöldborsó\":\"50 dkg (friss vagy fagyasztott)\",\"vöröshagyma\":\"1 fej\",\"liszt\":\"1 evőkanál\",\"tejföl\":\"2 dl\",\"só\":\"ízlésre\",\"cukor\":\"1 kávéskanál\",\"olaj\":\"2 evőkanál\",\"petrezselyem\":\"1 csokor\"}', '1. A hagymát apróra vágjuk, az olajon megpirítjuk.\n2. Hozzáadjuk a lisztet, majd a zöldborsót és kevés vizet.\n3. Puhára főzzük, majd hozzáadjuk a tejfölt, sót és cukrot.\n4. Finomra vágott petrezselyemmel megszórva tálaljuk, tojással vagy sült kolbásszal.', 'zoldborsoFozelek.jpg', 'https://www.nosalty.hu/recept/zoldborso-fozelek'),
(70, 'főétel', 'Káposztás tészta', 'édes;tészta', 60, 6, '{\"tészta\":\"50 dkg\",\"fejes káposzta\":\"1 kg\",\"vaj\":\"10 dkg\",\"cukor\":\"10 dkg\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\",\"mák\":\"tálaláshoz\"}', '1. A káposztát vékonyra metéljük, és a vajon megpároljuk.\n2. Sóval, borssal és cukorral ízesítjük.\n3. A tésztát kifőzzük, és a káposztával összekeverjük.\n4. Tálaláskor mákkal megszórjuk.', 'kaposztasTeszta.jpg', 'https://www.mindmegette.hu/recept/edes-kaposztas-teszta'),
(71, 'főétel', 'Túros csiga', 'sós;sütemény', 90, 8, '{\"liszt\":\"50 dkg\",\"túró\":\"40 dkg\",\"tejföl\":\"2 dl\",\"tojás\":\"2 db\",\"élesztő\":\"2 dkg\",\"só\":\"1 teáskanál\",\"vaj\":\"sütéshez\"}', '1. Az élesztőt felfuttatjuk a meleg tejfölben.\n2. A lisztet összegyúrjuk a túróval, tojással, sóval és az élesztős tejföllel.\n3. Kelni hagyjuk 1 órát.\n4. A tésztát kinyújtjuk, feltekerjük, és csigákat formázunk.\n5. Vajazott tepsiben 180°C-on 25 percig sütjük.', 'turosCsiga.jpg', 'https://www.nosalty.hu/recept/turos-csiga'),
(72, 'desszert', 'Málnás piskóta', 'édes;gyümölcsös', 45, 8, '{\"tojás\":\"4 db\",\"cukor\":\"20 dkg\",\"liszt\":\"20 dkg\",\"sütőpor\":\"1 csomag\",\"málna\":\"30 dkg\",\"tejszín\":\"3 dl\",\"porcukor\":\"díszítéshez\"}', '1. A tojásokat a cukorral habosra keverjük.\n2. Hozzáadjuk a lisztet és sütőport.\n3. Tepsiben 180°C-on 20 percig sütjük.\n4. Kihűtés után a piskótát tetejére helyezzük a málnát és a felvert tejszínhabot.\n5. Porcukorral megszórva tálaljuk.', 'malnasPiskota.jpg', 'https://www.mindmegette.hu/recept/malnas-piskota'),
(73, 'főétel', 'Sárgarépafőzelék', 'vegetáriánus;főzelék', 50, 4, '{\"sárgarépa\":\"80 dkg\",\"vöröshagyma\":\"1 fej\",\"liszt\":\"1 evőkanál\",\"tejföl\":\"2 dl\",\"só\":\"ízlésre\",\"cukor\":\"1 evőkanál\",\"olaj\":\"2 evőkanál\",\"kömény\":\"1 teáskanál\"}', '1. A sárgarépát meghámozzuk, és karikákra vágjuk.\n2. A hagymát apróra vágjuk, az olajon megpirítjuk, hozzáadjuk a köményt és lisztet.\n3. Hozzáadjuk a répát, és kevés vízzel puhára főzzük.\n4. A tejfölt hozzáadjuk, és összeforraljuk. Tojással tálaljuk.', 'sargarepaFozelek.jpg', 'https://www.nosalty.hu/recept/sargarepafozelek'),
(74, 'főétel', 'Görög saláta', 'saláta;nyári', 20, 4, '{\"paradicsom\":\"4 db\",\"uborka\":\"1 db\",\"lilahagyma\":\"1 fej\",\"sajt\":\"20 dkg\",\"olívabogyó\":\"15 dkg\",\"olívaolaj\":\"3 evőkanál\",\"oregano\":\"1 teáskanál\",\"citromlé\":\"1 evőkanál\"}', '1. A paradicsomot és uborkát kockára vágjuk.\n2. A hagymát vékony karikákra metéljük.\n3. A sajtot kockára vágjuk.\n4. Összekeverjük az olívabogyóval, olívaolajjal, citromlével és oreganóval.\n5. Hűtőben 1 órát érleljük a tálalás előtt.', 'gorogSalata.jpg', 'https://www.nosalty.hu/recept/original-gorog-salata'),
(75, 'desszert', 'Tiramisu', 'édes;olasz', 120, 8, '{\"mascarponé\":\"50 dkg\",\"tojás\":\"4 db\",\"cukor\":\"15 dkg\",\"kávé\":\"3 dl\",\"babapiskóta\":\"30 dkg\",\"kakaópor\":\"díszítéshez\",\"rum\":\"2 evőkanál\"}', '1. A tojások sárgáját a cukorral habosra keverjük, hozzáadjuk a mascarponét.\n2. A fehérjékből kemény habot verünk, és óvatosan a masszába keverjük.\n3. A babapiskótát a rumos kávéba mártjuk.\n4. Tálba rétegezzük a piskótát és a krémet. 4 órára hűtőbe tesszük.\n5. Tálalás előtt kakaóporral meghintjük.', 'tiramisu.jpg', 'https://www.mindmegette.hu/recept/eredeti-tiramisu'),
(76, 'főétel', 'Zöldbabos rizses hús', 'hús;rizses', 60, 4, '{\"csirkemell\":\"60 dkg\",\"rizs\":\"30 dkg\",\"zöldbab\":\"40 dkg\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"3 gerezd\",\"olaj\":\"3 evőkanál\",\"só\":\"ízlésre\",\"bors\":\"ízlésre\"}', '1. A csirkét kockára vágjuk, sózzuk, borsozzuk.\n2. Az olajon megpirítjuk a hagymát, hozzáadjuk a húst, és átsütjük.\n3. Hozzáadjuk a rizst, felöntjük vízzel, és puhára főzzük.\n4. Az utolsó 10 percben hozzáadjuk a zöldbabot.', 'zoldbabosRizsesHus.jpg', 'https://www.nosalty.hu/recept/zoldbabos-rizses-hus'),
(77, 'desszert', 'Puncs szelet', 'édes;sütemény', 180, 12, '{\"liszt\":\"30 dkg\",\"cukor\":\"20 dkg\",\"tojás\":\"4 db\",\"vaj\":\"20 dkg\",\"tej\":\"2 dl\",\"rum\":\"2 evőkanál\",\"kakaó\":\"2 evőkanál\",\"vanília\":\"1 rúd\"}', '1. A tojások sárgáját a cukorral habosra keverjük.\n2. Hozzáadjuk az olvasztott vajat, rumot, vaníliát és a lisztet.\n3. A fehérjékből kemény habot verünk, és óvatosan a masszába keverjük.\n4. Tepsiben 180°C-on 25 percig sütjük. Kihűtés után kockákra vágjuk.', 'puncsSzelet.jpg', 'https://www.mindmegette.hu/recept/puncs-szelet'),
(78, 'főétel', 'Korianderes krumplifőzelék', 'főzelék', 25, 4, '{\"sertészsír\":\"0.5 evőkanál\",\"vöröshagyma\":\"1 fej\",\"fokhagyma\":\"2 gerezd\",\"babérlevél\":\"2 db\",\"burgonya\":\"1 kg\",\"só\":\"ízlésre\",\"fűszerpaprika\":\"0.5 teáskanál\",\"tej\":\"250 ml\",\"víz\":\"800 ml\",\"ételecet\":\"1 evőkanál (10%-os)\",\"koriander\":\"1 csokor, friss\",\"tejföl\":\"175 g\",\"finomliszt\":\"50 g\"}', '1. Zsírt melegítünk egy lábasban, és a finomra vágott vörös- és fokhagymát a babérral együtt közepes hőfokon 5 percig dinszteljük rajta.\n2. Hozzáadjuk a kb. 2 cm-es kockákra vágott krumplit. Sózzuk és megszórjuk a fűszerpaprikával, majd felöntjük a tej és víz keverékével.\n3. Közepes hőfokon puhára főzzük a krumplit.\n4. A habaráshoz a tejfölben elkeverjük a lisztet, hőkiegyenlítünk (azaz merünk hozzá pár kanállal a krumpli főzőlevéből és elkeverjük), majd besűrítjük vele a főzeléket, végül az ecettel és a frissen aprított korianderrel beállítjuk a végleges ízeket. Tálaljuk a főzeléket, ízlés szerint akár feltéttel.', 'korianderesKrumplifozelek.jpg', 'https://streetkitchen.hu/levesek-es-fozelekek/korianderes-krumplifozelek/'),
(79, 'egyéb', 'Kovászos uborka', 'savanyúság;kovász;nyári', 30, 4, '{\"uborka\":\"3 kg\",\"víz\":\"4 l\",\"só\":\"3 ek\",\"fokhagyma\":\"4 gerezd\",\"kapor\":\"1 csokor\",\"kenyér\":\"1 szelet\"}', '1. Az uborkákat alaposan mossuk meg, de ne hámozzuk meg. A végeit vágjuk le egy kicsit.\n2. Készítsük ki az alaposan kimosott 5 literes befőttes üvegünket, majd a rakjuk bele az uborkákat, közéteve a megtisztított fokhagymát, tormát és kaport.\n3. Forraljunk fel vizet, adjuk hozzá a sót, és keverjük, amíg teljesen fel nem oldódik. Hagyjuk langyosra hűlni.\n4. Öntsük a langyos sós vizet az uborkákra úgy, hogy teljesen ellepje őket.\n5. Fedjük le egy tányérral vagy törlőkendővel, és hagyjuk szobahőmérsékleten fermentálódni 3-4 napig. A fermentálás ideje függ a hőmérséklettől - minél melegebb van, annál gyorsabban kész.\n6. Amikor az uborkák megfelelően savanyúak (de még ropogósak), tegyük őket a hűtőbe, ahol tovább lassan fermentálódnak, de hosszabb ideig elállnak.', 'koviubi.jpg', 'https://www.nosalty.hu/recept/kovaszos-uborka-klasszikus');

--
-- Indexek a kiírt táblákhoz
--

--
-- A tábla indexei `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- A tábla indexei `recept`
--
ALTER TABLE `recept`
  ADD PRIMARY KEY (`id`);

--
-- A kiírt táblák AUTO_INCREMENT értéke
--

--
-- AUTO_INCREMENT a táblához `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT a táblához `recept`
--
ALTER TABLE `recept`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=80;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
